# Generated by Django 3.1.7 on 2021-03-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='specialty',
            new_name='speciality',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
